development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: interngr_test
  pool: 5
  host: localhost
  port: 5432
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: interngr
  username: 
  password: 
  host: localhost
  port: 5432   
